<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Category extends Model
{
    /**
     * Set default attributes
     * @var array
     */
    protected $attributes = [
        'parent_id' => 0
    ];

    protected $fillable = [
        'name', 'slug', 'parent_id', 'is_active', 'image'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        // before create
        static::creating(function ($category) {
            $category->updateSlug();

            // upload image
            $category->uploadImage();
        });

        // before update
        static::updating(function ($category) {
            $category->updateSlug();
        });

        static::deleting(function ($category) {
            $category->deleteRelatedImage();
        });
    }

    public function deleteRelatedImage()
    {
        @Storage::delete($this->getOriginal('image'));
    }

    /**
     * Get the route key for the model.
     *
     * @return string
     */
    public function getRouteKeyName()
    {
        return 'slug';
    }

    /**
     * Create and update image
     */
    public function uploadImage()
    {
        if ($this->image) {
            // set image
            $file_name = $this->image->getClientOriginalName();
            $file_name = time() . '-' . $file_name;
            $path = $this->image->storeAs(PATH_UPLOAD, $file_name);
            $this->image = $path;
        }
    }


    public function updateSlug()
    {
        $this->slug = str_slug($this->name, "-");
    }

    /**
     * Define Relationship one-to-many
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function articles()
    {
        return $this->hasMany('App\Models\Article');
    }

    public function children()
    {
        return $this->hasMany("App\Models\Category", "parent_id");
    }

    public function parent()
    {
        return $this->belongsTo("App\Models\Category", "parent_id");
    }

    public static function getListCategory()
    {
        return self::get();
    }

    public static function getCategoryAndCountPosts()
    {
        return self::withCount('articles')->get();
    }

    public function getListCategoryPaginate()
    {
        return self::with('parent')->latest()->paginate();
    }

    public static function getCategoryBySlug($slug)
    {
        return self::where(['slug' => $slug])->first();
    }

}
