<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Tutorial extends Model
{
    protected $fillable = ['name', 'category_id', 'is_active'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        // before create
        static::creating(function ($tutorial) {
            $tutorial->createOrUpdateSlug();

        });

        // before update
        static::updating(function ($category) {
            $category->createOrUpdateSlug();
        });
    }

    public function createOrUpdateSlug()
    {
        $this->slug = str_slug($this->name);
    }

    public function category()
    {
        return $this->belongsTo('App\Models\Category');
    }

    public function articles()
    {
        return $this->hasMany('App\Models\Article');
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }
}
